apiVersion: v1
kind: PersistentVolume
metadata:
  name: p-volume-tw
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/local/tomcat/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-tw
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
